eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
server:
  port: 10001
spring:
  application:
    name: zuul
##配置zuul网关
zuul:
  routes:
    api-a:
      path: /consumer-zuul/**
      service-id: eureka-consumer
    api-b:
      path: /provider-zuul/**
      service-id: eureka-provider
